# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20160729_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.CharField(default='Null', max_length=45),
            preserve_default=False,
        ),
    ]
