# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 00:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0008_course'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('courseManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
