# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0009_auto_20160805_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='first_course',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='second_course',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='third_course',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
