# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 15:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('email_val', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='email',
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
